"""Initial migration.

Revision ID: 23e058aeeef9
Revises: 
Create Date: 2024-12-16 19:21:34.765688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e058aeeef9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_exercises')
    op.drop_table('user')
    op.drop_table('exercise_group')
    op.drop_table('choice')
    op.drop_table('exercise')
    op.drop_table('competition_participants')
    op.drop_table('student')
    op.drop_table('class')
    op.drop_table('competition_student_stats')
    op.drop_table('competition')
    op.drop_table('group_exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_exercises',
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['exercise_group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'exercise_id')
    )
    op.create_table('competition',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_started', sa.DATETIME(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), nullable=False),
    sa.Column('code', sa.INTEGER(), nullable=True),
    sa.Column('competition_started', sa.BOOLEAN(), nullable=True),
    sa.Column('competition_ended', sa.BOOLEAN(), nullable=True),
    sa.Column('current_exercise_id', sa.INTEGER(), nullable=True),
    sa.Column('current_student_index', sa.INTEGER(), nullable=True),
    sa.Column('used_exercise_ids', sa.TEXT(), nullable=True),
    sa.Column('active_student_ids', sa.TEXT(), nullable=True),
    sa.Column('last_player_chances', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['current_exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['exercise_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_student_stats',
    sa.Column('competition_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('competition_id', 'student_id')
    )
    op.create_table('class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_participants',
    sa.Column('competition_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('competition_id', 'student_id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('exercise_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('correct_answer', sa.TEXT(), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=150), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('class_exercises',
    sa.Column('class_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'exercise_id')
    )
    # ### end Alembic commands ###
